### ISSUE TITLE
Broken URL in section 2.1 Architectural Overview

### ISSUE THREAD

**Issue by franknitty69** [3drobotics/solodevguide#103]
Paragraph 3 contains a broken url

The Linux system controls high-level operation of the copter: **smart shots**, camera and gimbal control, mobile app communication, and accessory interaction are all implemented in this layer.

the link, **smart shots**, links to http://dev.3dr.com/smartshot.html which is dead.

**Comment by tcr3dr** [comment]
Thanks @franknitty69!
