### ISSUE TITLE
What is the license of this guide?

### ISSUE THREAD

**Issue by tcr3dr** [3drobotics/solodevguide#112]
I prefer [CC-BY-SA 4.0 for documentation](http://creativecommons.org/licenses/by-sa/4.0/legalcode.txt), [CC0 for code samples](http://creativecommons.org/publicdomain/zero/1.0/legalcode.txt), and MIT/ASL2 dual license for code (solo-utils).

/cc @mrpollo

**Comment by mrpollo** [comment]
@bbasso can you help us decide on license.

**Comment by bbasso** [comment]
I like CC BY-SA 4.0 of the docs, same as the open source policy.  http://3drobotics.com/open-source-policy/

**Comment by tcr3dr** [comment]
Done. https://github.com/3drobotics/solodevguide/pull/114
