### ISSUE TITLE
Make it clear that solo-utils is on Solo

### ISSUE THREAD

**Issue by asetapen** [3drobotics/solodevguide#117]
In the "Configure tools" section, I assumed solo-utils was on my host. But alas, it's on Solo! Make this clear.

**Comment by hamishwillee** [comment]
Agree, confusing. I'll try fix this now.

**Comment by hamishwillee** [comment]
Hi Adam, 

Thanks very much - I had subedited this and thought we'd covered the issue. Had not.

This should be fixed by #120. The patch goes a little further and does a page restructure. There is still one open question #119 which you may be able to help with?

Cheers
H

**Comment by tcr3dr** [comment]
(To confuse things moreso, solo-utils is now solo-cli on PC.)

**Comment by tcr3dr** [comment]
I would consider this resolved by #142 once it's more complete.

**Comment by hamishwillee** [comment]
#142 is in, and I think this is clear. Closing.
