### ISSUE TITLE
Solo utils - what are the initialisation prompts referred to?

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/solodevguide#119]
in [Solo Utils / Connecting to the Internet](http://dev.3dr.com/starting-utils.html#connecting-to-the-internet) it says:

> Follow the prompts on first initialization to create a reverse SSH tunnel to your host computer, enabling direct Internet access from Solo: `solo-utils tunnel-start`

Then it shows how to set up the SSH tunnel. The question is, what is "first initialisation here"? Are you trying to say that there will be prompts after you run `solo-utils tunnel-start`?

**Comment by tcr3dr** [comment]
This no longer has any prompts, or exists.
