### ISSUE TITLE
Configure tools requires `tunnel-start`

### ISSUE THREAD

**Issue by tcr3dr** [3drobotics/solodevguide#125]
**Author:** Daniel Nugent
**Page:** http://dev.3dr.com/

Configure tools requires `tunnel-start`

Connecting to the internet should come before. 

Also anytime steps switch between host and solo for running terminal commands a note should be made(a note was made for switching to host but never for switching back to solo). I just tried to run solo-utils on my host machine because I was never instructed to run it on solo. What may be a face palm for me, may be pain point for beginner.

**Comment by djnugent** [comment]
Man does the entire message really need to be the subject of the issue haha. Also it didn't link the page properly. I was on starting-utils

**Comment by djnugent** [comment]
feedback tool--

**Comment by djnugent** [comment]
Dead link in the "tip" on internet connection stuff

**Comment by hamishwillee** [comment]
@djnugent Thanks for that. I believe my patch of yesterday (now) fixes this (I fixed up the tip, and put "connect to internet" first).
https://github.com/3drobotics/solodevguide/pull/120

**Comment by tcr3dr** [comment]
I believe this is more adequately addressed by the docs, and clarifying the host/solo distinction is #142 and #143.
