### ISSUE TITLE
"Battery too low for takeoff ... ready for takeoff"

### ISSUE THREAD

**Issue by TaylorR137** [3drobotics/solodevguide#126]
This bug lways makes me laugh but its somewhat embarrassing when showing it off to friends!

**Comment by hamishwillee** [comment]
Hi @TaylorR137, whether it is a bug or not I don't know. But it isn't a bug with the Solo Dev Guide, so I'm closing it. Suggest you raise on the ArduPilot/APM forums.

**Comment by nick3dr** [comment]
This is an issue with the android app, being tracked internally. Thanks.
(APP-1456)

On Sat, Sep 12, 2015 at 4:35 PM, Hamish Willee <notifications@github.com>
wrote:

> Hi @TaylorR137 <https://github.com/TaylorR137>, whether it is a bug or
> not I don't know. But it isn't a bug with the Solo Dev Guide, so I'm
> closing it. Suggest you raise on the ArduPilot/APM forums.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3drobotics/solodevguide/issues/126#issuecomment-139828970>
> .
>



-- 
◤*Nick Speal*
    engineering project manager
    3D Robotics
    415.599.1404
    website <http://www.3dr.com/> | facebook
<http://www.facebook.com/3drobotics> | Instagram
<http://www.instagram.com/3drobotics>

**Comment by tcr3dr** [comment]
That is pretty funny, though. "Cannot arm. Too much arming"
