### ISSUE TITLE
Make it clear how you control the gimbal/not from DK

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/solodevguide#131]
From Gitter DK channel

> Is there a way to control SOLO's gimbal using Dronekit? Also what are the angle limitations in pitch,roll and yaw for the gimbal?

> You can find a very crude example here: https://github.com/3drobotics/demo-realtimeearth/blob/master/example.py#L71
You should not need the "for i in range(0, 5):" loops, this was over a very lossy UDP connection
We will eventually add controls for the gimbal to DroneKit itself.

IMO we need to make any DK limitations clear too and point to where people go to control the gimbal now.

**Comment by tcr3dr** [comment]
This is a DK issue. https://github.com/dronekit/dronekit-python/issues/312
