### ISSUE TITLE
Enable controller/Solo to connect to users Wifi existing network

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/solodevguide#132]
From @OXINARF in https://github.com/3drobotics/solodevguide/issues/123#issuecomment-140050138

> What would be cool (and possible) was that solo-utils had an option so that the Solo's controller would connect to the user/developer's Wifi network and act like a true router. That way the Ethernet cable wouldn't be needed.

**Comment by tcr3dr** [comment]
This is going to replace `solo-utils tunnel-start`. This is definitely a huge usability issue and we can definitely support this type of connectivity.

**Comment by tcr3dr** [comment]
See #46.

**Comment by tcr3dr** [comment]
This is now implemented. See #46 for resolution.
