### ISSUE TITLE
Solo-utils improvements

### ISSUE THREAD

**Issue by tcr3dr** [3drobotics/solodevguide#134]
**Author:** Jaime Machuca
**Page:** http://dev.3dr.com/starting-utils.html

Its not clear where solo-utils live, it should be more clear where to run the solo-utils scripts. Make it clear you have to be ssh into solo and that these scripts need to run on solo. The installation of pip, needs to be done after the solo is connected to the internet using the tunnel. So I would change the order, of Configure Tools and Connecting to the Internet.

**Comment by jmachuca77** [comment]
related to #125

**Comment by hamishwillee** [comment]
I think all of these are addressed by https://github.com/3drobotics/solodevguide/pull/120 which is merged but not yet live. @jmachuca77  Can you check?

**Comment by jmachuca77** [comment]
Yes, it seems they are. When I left feedback through the page feedback I did not realize this issues were already addressed. I think this can be closed.

**Comment by hamishwillee** [comment]
@jmachuca77 - no way for you to know until it goes live. Keep those fixes coming - really appreciate the information.
