### ISSUE TITLE
DroneKit example page needs "import time"

### ISSUE THREAD

**Issue by tcr3dr** [3drobotics/solodevguide#146]
Otherwise you get 

```
(env)➜  ok1  python run.py
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    time.sleep(5)
NameError: name 'time' is not defined
```

**Comment by hamishwillee** [comment]
Why not just `import time`?

**Comment by tcr3dr** [comment]
I think the page should also `import time`

**Comment by hamishwillee** [comment]
#155 corrects the text. The latest example source code already has the import statement.

**Comment by tcr3dr** [comment]
Coolio. I copied from the text, was surprised, but you're correct.
