### ISSUE TITLE
Mis-reporting my name through this Olark thing. I'm submitting my GH username @frijol and it still says Kelsey

### ISSUE THREAD

**Issue by tcr3dr** [3drobotics/solodevguide#177]
**Author:** @frijol
**Page:** http://dev.3dr.com/starting-utils.html#connecting-to-solo-and-the-internet

Mis-reporting my name through this Olark thing. I'm submitting my GH username @frijol and it still says Kelsey

**Comment by Frijol** [comment]
huh I guess it worked this time

**Comment by tcr3dr** [comment]
Closing in favor of #101. Feedback should be reported there.
