### ISSUE TITLE
VLC Live view not working

### ISSUE THREAD

**Issue by djnugent** [3drobotics/solodevguide#194]
Followed the guide with no success. Could not view VLC feed on windows or Ubuntu

**Comment by TaylorR137** [comment]
Open the file in VLC then run the command and it will connect. Then open
the mobile app.

**Comment by djnugent** [comment]
Thanks that worked!

**Comment by tcr3dr** [comment]
@TaylorR137 thanks for the input! Made that more clear in the guide.
