### ISSUE TITLE
Sidebar corruption

### ISSUE THREAD

**Issue by djnugent** [3drobotics/solodevguide#198]
The sidebar loses items after an item is clicked. The only way to restore it is to refresh the page.

![sidebar mess up](https://cloud.githubusercontent.com/assets/6732731/10440720/91b9c4d8-70f6-11e5-800e-8df3b65fa7f5.PNG)

**Comment by tcr3dr** [comment]
@djnugent What are the full steps to reproduce this?

**Comment by djnugent** [comment]
Navigate to main page. Click on an item in the sidebar.

I can only get it happen on Win 10 chrome. Let me try to restart chrome.

**Comment by djnugent** [comment]
Issue persists with restart. Chrome Version 45.0.2454.101 m

**Comment by hamishwillee** [comment]
@djnugent Based on your screenshot this is (IMO) a variant of #121 - essentially if you have a search term it persists even through refreshes and that is why only some of the items are shown (see screenshot - you have "git" there).

The "workaround" is to delete the search term. This is broken though!

Close if you agree!

**Comment by djnugent** [comment]
Yes that is the issue.

**Comment by hamishwillee** [comment]
Closing. Dupicate of #121
