### ISSUE TITLE
Solo Provision command can't be found 

### ISSUE THREAD

**Issue by chasesutton** [3drobotics/solodevguide#201]
![screen shot 2015-10-19 at 6 01 52 pm](https://cloud.githubusercontent.com/assets/4250618/10595322/99d7c53a-768b-11e5-8f2d-97acfb68b6d3.png)
Once I reach this step, http://dev.3dr.com/starting-network.html#optimizing-ssh-access, I'm not able to run the Solo Provision command.

**Comment by tcr3dr** [comment]
@chasesutton You should run the `solo` command on your computer. It looks like you are logged into the terminal on solo (identified by the `root@3dr_solo` bit.)
