### ISSUE TITLE
Wifi support and controller version mismatch

### ISSUE THREAD

**Issue by tcr3dr** [3drobotics/solodevguide#203]
**Author:** Ken McGuire
**Page:** http://dev.3dr.com/starting-utils.html

Just an FYI
Trying to run solo wifi ....
It says:
error: expecting Controller to be EXACTLY EQUAL TO 1.1.15 your controller version: 1.2.0 please flash your Controller with 1.1.15.....
Well, I just updated my Solo &amp; controller yesterday to 1.2.0. Maybe you should update solo-utils when a new release of Solo firmware comes out.

**Comment by hamishwillee** [comment]
I think this is a duplicate of #199

**Comment by tcr3dr** [comment]
I've been in contact with Ken, `solo-cli wifi` version requirements are no longer a blocker for him.
