### ISSUE TITLE
Local build of master does not display sidebar

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/solodevguide#237]
Local build off master following merge of #210 does not display sidebar. Note that toggling the sidebar button up the top does nothing on local build.

![image](https://cloud.githubusercontent.com/assets/5368500/11797678/e7c79ee6-a318-11e5-9bba-5685e08418b7.png)

**Comment by mrpollo** [comment]
just pulled and I can see the sidebar, I also noticed on your screenshot the hamburger icon is active, if you click that the sidebar is back!

**Comment by hamishwillee** [comment]
The hamburger doesn't work, or I wouldn't have posted the bug. That said, if it works for you there must be some other problem. Playing around now.
