### ISSUE TITLE
starting-utils is not up-to-date

### ISSUE THREAD

**Issue by JonasVautherin** [3drobotics/solodevguide#245]
To install `solo-cli`, the [dev page](http://dev.3dr.com/starting-utils.html) says to use the following command:

    pip install -UI git+https://github.com/3drobotics/solo-cli

which gives me a segmentation fault (Arch Linux). The [`solo-cli` page](https://github.com/3drobotics/solo-cli) proposes:

    sudo pip uninstall soloutils || true
    sudo pip uninstall solo-cli -y || true
    sudo pip install https://github.com/3drobotics/solo-cli/archive/master.zip --no-cache-dir

which works for me (Arch Linux).

**Comment by hamishwillee** [comment]
Thanks @JonasVautherin 

In an ideal world you really should not need to follow those second instructions unless you're updating from the old solo-cli. Even so, since you found them useful and there is no harm in it I've added them as an alternative in #246
