### ISSUE TITLE
Question - How many cores does the Solo A9 processor have?

### ISSUE THREAD

**Issue by alexblack** [3drobotics/solodevguide#309]
I'm curious if it has multiple cores or not, thanks!

https://en.wikipedia.org/wiki/ARM_Cortex-A9

**Comment by franknitty69** [comment]
Solo uses the Freescale i.MX6 Solo (1Ghz, 1 CPU core w/VPU and GPU

**Comment by alexblack** [comment]
Thanks. What is a VPU?

**Comment by proficnc** [comment]
Video Processing Unit

**Comment by alexblack** [comment]
Ah, cool. What is the VPU used for in normal operation? Can it be used via
code/API?

**Comment by fraserharris** [comment]
@alexblack possible this: https://github.com/Freescale/libimxvpuapi
