### ISSUE TITLE
How to connect Odroid to Pixhawk2?

### ISSUE THREAD

**Issue by pchatrath** [3drobotics/solodevguide#311]
Hello,

 @tcr3dr 
I wish to create an ir tracker uav by connecting IR camera like pointgrey chameleon 3 ir camera to 3DR solo. I was thinking to connect a Odroid to Pixhawk 2 and make it the main brain which will take data from senor and pass commands to pixhawk using mavros. For that how do I connect odroid to Pixhawk?

Also for this application can i some how use the other processor available on 3DR solo. 

Thanks

**Comment by hamishwillee** [comment]
@pchatrath I very much doubt 3DR will have time to provide more information than that already made available on http://dev.3dr.com/. 
This sort of question best asked on the [discussion boards](https://discuss.dronekit.io/c/solo-development).

That said, there is a very capable companion computer on the vehicle already. I imagine attaching an odroid as well doesn't make much sense.

**Comment by pchatrath** [comment]
Thanks @hamishwillee I will ask the question at discussion board

**Comment by jmachuca77** [comment]
Try this:

http://ardupilot.org/dev/docs/odroid-via-mavlink.html

Pixhawk2 is no different than a regular Pixhawk, just connect to the serial port on the accessory bay or on the gimbal connector instead of the telemetry port.

**Comment by pchatrath** [comment]
Thanks @jmachuca77 . Will try it out
