### ISSUE TITLE
SimpleDrone

### ISSUE THREAD

**Issue by amyjchen** [3drobotics/solodevguide#319]
Where does SimpleDrone in the skywriter example come from and how can I get it?

**Comment by hamishwillee** [comment]
SimpleDrone is a basic API wrapper for operations to take off and move the vehicle. Looking at the requirements.txt I imagine someone forked this project https://github.com/djnugent/dronedirect and renamed it to SimpleDrone but forgot to move the requirements link. 

@mrpollo Do you know where this moved to?

@amyjchen YOu could easily just replace this library with your own takeoff and move commands. It's only used to simplify the example.

**Comment by mrpollo** [comment]
sadly i don't @hamishwillee  :(
