### ISSUE TITLE
Have the Controller able to talk to a wifi network

### ISSUE THREAD

**Issue by tcr3dr** [3drobotics/solodevguide#46]
This would replace the crude "tunnel" system.

The Controller has the capacity to act not only as an AP (allowing Solo to connect to it) but also as in STA mode (connecting to a different wifi network). This is enabled through `/etc/sololink.conf` and the configuration can happen from the command line.

The next step is configuring NAT so that Solo can act as though it were connected to the network as well.

Lastly, we need to the capacity to change this wifi network from Solo, possibly by SSHing into Artoo. Do we hardcode this configuration, so Solo always tries to connect to a specific Wifi network?

**Comment by hamishwillee** [comment]
> Lastly, we need to the capacity to change this wifi network from Solo, possibly by SSHing into Artoo. Do we hardcode this configuration, so Solo always tries to connect to a specific Wifi network?

My 2 bits ... 

* Controller/Solo shouldn't "depend" on external network which implies to me that it shouldn't always try to connect to anything other than each other. Probably not what you were suggesting!
* My preference as a user would be that setting up a "connect to network" would be a UI option in Artoo. This would allow you to select network and store your preference. This might at some point be used for auto-firmware downloads also. 
* How is the controller going to find Solo and visa versa on an arbitrary network where IPs are dynamically allocated?

**Comment by kevinmehall** [comment]
I got this working.

Kernel option `IP_NF_FILTER` needs to be enabled.

I've compiled it as a module: https://drive.google.com/file/d/0BwstB7gcMKACeFBKR0hIakgxeTA/view?usp=sharing

```
scp iptable_filter.ko root@10.1.1.1:/lib/modules/3.10.17-rt12-1.0.0_ga+gdc67983/kernel/net/ipv4/netfilter/
```

```
insmod /lib/modules/3.10.17-rt12-1.0.0_ga+gdc67983/kernel/net/ipv4/netfilter/iptable_filter.ko
echo 1 > /proc/sys/net/ipv4/ip_forward
```

`nano /etc/wpa_client.conf`, with

```
network={
  ssid=""
  psk=""
}
```

Configure dnsmasq
```
nano /etc/dnsmasq.conf
```

change:

```
# No default router
dhcp-option=3

# No DNS server
dhcp-option=6
```

to

```
# Default gateway
dhcp-option=3,10.1.1.1

# DNS server
dhcp-option=6,8.8.8.8
```

`/etc/init.d/dnsmasq restart`

Connect to the network:
```
wpa_supplicant -i wlan0 -c /etc/wpa_client.conf -B
udhcpc -i wlan0
```

Enable NAT:
```
iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
iptables -A FORWARD -i wlan0 -o wlan0-ap -j ACCEPT
iptables -A FORWARD -i wlan0-ap -o wlan0 -j ACCEPT
```

**Comment by kevinmehall** [comment]
@hamishwillee 
> How is the controller going to find Solo and visa versa on an arbitrary network where IPs are dynamically allocated?

The controller acts as both a client to the upstream network and an access point. Solo and computers connect to the SoloLink network and receive 10.1.1.x IPs from dnsmasq on the controller as usual,  but the controller provides internet access via NAT to the upstream interface.

**Comment by hamishwillee** [comment]
Thanks @kevinmehall - very succinct

**Comment by tcr3dr** [comment]
An early version of this setup is now integrated into http://github.com/3drobotics/solo-cli via the `solo wifi` command!

A next step for this command is to make it a "permanent" install, i.e. the Controller continues to connect after reboot, and the `solo wifi` command can add or remove connections it listens to.

I'll address that type of functionality in a separate issue.
