### ISSUE TITLE
How do you update Solo from the command line?

### ISSUE THREAD

**Issue by tcr3dr** [3drobotics/solodevguide#5]
* How do you factory reset Solo?
* How do you reset solo to a known firmware image?

**Comment by tcr3dr** [comment]
This is now covered by https://github.com/3drobotics/solo-cli

**Comment by emogenet** [comment]
I am trying to update my controller to the latest (it is now stuck at v0.6.14)
When I try the command "solo update controller latest", it dumps an error.
Looking at the python code, it looks like the code is not finished. In particular,
the variable SERVERADDR is undefined.

**Comment by tcr3dr** [comment]
Solo updating is blocked but should be added back in shortly: https://github.com/3drobotics/solo-cli/issues/8
