### ISSUE TITLE
Max amperage on 5V pins on accessory bay

### ISSUE THREAD

**Issue by dmoroni** [3drobotics/solodevguide#56]
The accessory bay pinout needs a max amperage on pins 15 and 17 on the [accessory bay port spec](https://github.com/3drobotics/solodevguide/blob/master/book/hardware-accessorybay.md)

**Comment by tcr3dr** [comment]
@gussy can you confirm pins 15 and 17 on http://dev.3dr.com/hardware-accessorybay.html ?

**Comment by Gussy** [comment]
@tcr3dr Confirmed! That's good safe limit (it's bound by the wire gauge used).

**Comment by tcr3dr** [comment]
Sweet!
