### ISSUE TITLE
Fix link text in "Rules and Advice"

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/solodevguide#61]
[Rules and Advice](http://ffc6904fed514b42b88f87926328069c5c8149f4.s3-website-us-east-1.amazonaws.com/donts.html) has link text "Factory reset your Solo and Artoo to a known good state."

@mrpollo What is Artoo?

In addition, we might want to consider renaming this from donts.md to advice.md or similar.

**Comment by tcr3dr** [comment]
This is resolved. We mean "Controller" and the page is no starting-rules.md
