### ISSUE TITLE
Explaining ssh/rsync "solo:" alias

### ISSUE THREAD

**Issue by hamishwillee** [3drobotics/solodevguide#87]
The [DroneKit instructions](http://dev.3dr.com/example-dronekit.html) use command:
```
rsync -avz --exclude="*.pyc" --exclude="env" ./ solo:/opt/dkexample
```
However the target of `solo:` is not clear in this context. We do explain how you can set an alias for `root@10.1.1.10` in [Optimising ssh](http://dev.3dr.com/starting-network.html#optimizing-ssh) but for a newbie it isn't obvious that this also applies to rsync (and of course that advice was created "remote" from this page).

Should we expand this out, do we need an explanation, or can we assume people will "get this"? I would suggest minimally that we add a note to the "Optimizing" topic explaining that this optimisation is also useful for rsync.

**Comment by tcr3dr** [comment]
@hamishwillee This is actually an issue, it should be `root@10.1.1.10:/opt/...` in all those instances. The guide is correct that we should not be using the solo alias.

**Comment by hamishwillee** [comment]
@tcr3dr So just to be very clear it sounds like you are saying that in **both** dronekit and rsync docs we *should not* use the alias. Or are you saying that the rsync needs to change, but [Optimising ssh](http://dev.3dr.com/starting-network.html#optimizing-ssh) is OK because you can use the alias for SSH? The note in [Optimising ssh](http://dev.3dr.com/starting-network.html#optimizing-ssh) indicates that we use the expanded view in this guide (implicitly for SSH) but it doesn't explain what we *should* do for rsync.

Assuming you can't use the alias anywhere I propose to change the DK instructions  to:
```
rsync -avz --exclude="*.pyc" --exclude="env" ./ root@10.1.1.10:/opt/dkexample
```
In [Optimising ssh](http://dev.3dr.com/starting-network.html#optimizing-ssh) I would remove the whole section after "You can optimize this process further "

**Comment by tcr3dr** [comment]
See https://github.com/3drobotics/solodevguide/pull/206. It moves the Optimizing SSH section to advanced section, and removes the solo: prefix in the rest of the guide.

**Comment by hamishwillee** [comment]
Those were good fixes thanks.
